name: pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: install dependecies
        run: npm install --no-audit --no-fund --no-optional
      - name: Run build
        run: npm run build
      - name: Run lint
        run: npm run lint
      - name: Run Test
        run: npm run test